# Generated by Django 4.0.5 on 2022-06-01 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DEpartments',
            new_name='Depsxsxartments',
        ),
    ]
