# Generated by Django 4.0.5 on 2022-06-01 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0002_rename_departments_depsxsxartments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Depsxsxartments',
            new_name='Departments',
        ),
    ]
